"""
gold_paper_trade.py

Paper trading tracker for gold signals.
Uses live_signals.csv generated by production.py to track a £100,000 paper portfolio.

Usage:
    python3 gold_paper_trade.py
    
Automatically processes new signals since last run.
"""

import pandas as pd
import numpy as np
import json
import os
from datetime import datetime
from pathlib import Path

# Configuration
LIVE_SIGNALS_FILE = "live_outputs/live_signals.csv"
PORTFOLIO_FILE = "live_outputs/gold_paper_portfolio.json"
STARTING_CAPITAL = 100000


class PaperPortfolio:
    """Paper trading portfolio for gold"""
    
    def __init__(self, starting_capital=STARTING_CAPITAL):
        self.starting_capital = starting_capital
        self.cash = starting_capital
        self.position = 0  # 0=flat, 1=long
        self.entry_price = None
        self.entry_date = None
        self.trades = []
        self.equity_history = []
        self.last_processed_date = None
    
    def process_day(self, date, price, target_position, signal_info=None):
        """
        Process one trading day
        
        Args:
            date: Trading date
            price: Gold close price
            target_position: 0 or 1
            signal_info: Optional dict with classifier_signal, regressor_signal, etc.
        """
        # Handle position changes
        if self.position == 0 and target_position == 1:
            self.enter_long(date, price, signal_info)
        elif self.position == 1 and target_position == 0:
            self.exit_long(date, price, signal_info)
        
        # Update equity (includes unrealized P&L if long)
        self.update_equity(date, price, target_position)
        self.last_processed_date = date
    
    def enter_long(self, date, price, signal_info=None):
        """Enter long position"""
        self.position = 1
        self.entry_price = price
        self.entry_date = date
        
        signal_str = ""
        if signal_info:
            signal_str = f" | {signal_info.get('classifier_signal', 'N/A')} / {signal_info.get('regressor_signal', 'N/A')}"
        
        print(f"  📈 {date}: BUY at ${price:.2f}{signal_str}")
    
    def exit_long(self, date, price, signal_info=None):
        """Exit long position"""
        # Calculate P&L
        pnl_pct = (price / self.entry_price - 1) * 100
        pnl_gbp = self.cash * (pnl_pct / 100)
        self.cash += pnl_gbp
        
        # Record trade
        self.trades.append({
            "entry_date": self.entry_date,
            "exit_date": date,
            "entry_price": self.entry_price,
            "exit_price": price,
            "pnl_pct": pnl_pct,
            "pnl_gbp": pnl_gbp,
            "days_held": (date - self.entry_date).days,
            "equity": self.cash,
        })
        
        signal_str = ""
        if signal_info:
            signal_str = f" | {signal_info.get('classifier_signal', 'N/A')} / {signal_info.get('regressor_signal', 'N/A')}"
        
        print(f"  📉 {date}: SELL at ${price:.2f} | P&L: {pnl_pct:+.2f}% (£{pnl_gbp:+,.0f}){signal_str}")
        
        # Clear position
        self.position = 0
        self.entry_price = None
        self.entry_date = None
    
    def update_equity(self, date, price, position):
        """Update equity history (includes unrealized P&L)"""
        if position == 1 and self.entry_price:
            # Long: include unrealized P&L
            unrealized_pct = (price / self.entry_price - 1)
            unrealized_gbp = self.cash * unrealized_pct
            equity = self.cash + unrealized_gbp
        else:
            # Flat: just cash
            equity = self.cash
        
        self.equity_history.append({
            "date": date,
            "equity": equity,
            "position": position,
            "price": price,
        })
    
    def get_stats(self):
        """Calculate portfolio statistics"""
        if not self.equity_history:
            return {}
        
        df = pd.DataFrame(self.equity_history)
        df["returns"] = df["equity"].pct_change()
        
        # Overall metrics
        total_return = (self.cash / self.starting_capital - 1) * 100
        
        if df["returns"].std() > 0:
            sharpe = df["returns"].mean() / df["returns"].std() * np.sqrt(252)
        else:
            sharpe = 0
        
        max_dd = (df["equity"] / df["equity"].cummax() - 1).min() * 100
        
        # Trade metrics
        trades_df = pd.DataFrame(self.trades) if self.trades else pd.DataFrame()
        
        if len(trades_df) > 0:
            win_rate = (trades_df["pnl_pct"] > 0).mean() * 100
            avg_win = trades_df[trades_df["pnl_pct"] > 0]["pnl_pct"].mean() if (trades_df["pnl_pct"] > 0).any() else 0
            avg_loss = trades_df[trades_df["pnl_pct"] < 0]["pnl_pct"].mean() if (trades_df["pnl_pct"] < 0).any() else 0
            avg_days_held = trades_df["days_held"].mean()
        else:
            win_rate = 0
            avg_win = 0
            avg_loss = 0
            avg_days_held = 0
        
        return {
            "starting_capital": self.starting_capital,
            "current_cash": self.cash,
            "current_equity": df["equity"].iloc[-1],
            "total_return_pct": total_return,
            "sharpe_ratio": sharpe,
            "max_drawdown_pct": max_dd,
            "total_trades": len(self.trades),
            "win_rate_pct": win_rate,
            "avg_win_pct": avg_win,
            "avg_loss_pct": avg_loss,
            "avg_days_held": avg_days_held,
            "days_tracked": len(self.equity_history),
            "current_position": self.position,
            "entry_price": self.entry_price,
            "unrealized_pnl_pct": ((df["equity"].iloc[-1] / self.cash) - 1) * 100 if self.position == 1 else 0,
        }
    
    def save(self):
        """Save portfolio state to JSON"""
        state = {
            "starting_capital": self.starting_capital,
            "cash": self.cash,
            "position": self.position,
            "entry_price": self.entry_price,
            "entry_date": self.entry_date.isoformat() if self.entry_date else None,
            "last_processed_date": self.last_processed_date.isoformat() if self.last_processed_date else None,
            "trades": [{**t,
                       "entry_date": t["entry_date"].isoformat(),
                       "exit_date": t["exit_date"].isoformat()}
                      for t in self.trades],
            "equity_history": [{**e, "date": e["date"].isoformat()}
                               for e in self.equity_history],
        }
        
        Path(PORTFOLIO_FILE).parent.mkdir(parents=True, exist_ok=True)
        with open(PORTFOLIO_FILE, 'w') as f:
            json.dump(state, f, indent=2, default=str)
    
    @classmethod
    def load(cls):
        """Load portfolio state from JSON"""
        if not os.path.exists(PORTFOLIO_FILE):
            return cls()
        
        with open(PORTFOLIO_FILE, 'r') as f:
            state = json.load(f)
        
        portfolio = cls(state["starting_capital"])
        portfolio.cash = state["cash"]
        portfolio.position = state["position"]
        portfolio.entry_price = state["entry_price"]
        portfolio.entry_date = pd.Timestamp(state["entry_date"]) if state["entry_date"] else None
        portfolio.last_processed_date = pd.Timestamp(state["last_processed_date"]) if state["last_processed_date"] else None
        
        portfolio.trades = [{**t,
                            "entry_date": pd.Timestamp(t["entry_date"]),
                            "exit_date": pd.Timestamp(t["exit_date"])}
                           for t in state.get("trades", [])]
        
        portfolio.equity_history = [{**e, "date": pd.Timestamp(e["date"])}
                                    for e in state.get("equity_history", [])]
        
        return portfolio


def format_signal_summary(row):
    """Format signal info for display"""
    info = {}
    if 'classifier_signal' in row:
        info['classifier_signal'] = row['classifier_signal']
    if 'regressor_signal' in row:
        info['regressor_signal'] = row['regressor_signal']
    if 'combined_signal' in row:
        info['combined_signal'] = row['combined_signal']
    return info


def main():
    print("="*80)
    print("GOLD PAPER TRADING")
    print("="*80)
    
    # Check file exists
    if not os.path.exists(LIVE_SIGNALS_FILE):
        print(f"\n❌ Signals file not found: {LIVE_SIGNALS_FILE}")
        print("Please run production.py first to generate signals.")
        return
    
    # Load signals
    print(f"\n[1] Loading signals: {LIVE_SIGNALS_FILE}")
    signals_df = pd.read_csv(LIVE_SIGNALS_FILE)
    signals_df['date'] = pd.to_datetime(signals_df['date'])
    signals_df = signals_df.sort_values('date')
    
    print(f"    ✅ Loaded {len(signals_df)} signals")
    print(f"    Date range: {signals_df['date'].min().date()} to {signals_df['date'].max().date()}")
    
    # Load portfolio
    print(f"\n[2] Loading portfolio...")
    portfolio = PaperPortfolio.load()
    
    if portfolio.last_processed_date:
        print(f"    Resuming from {portfolio.last_processed_date.date()}")
        new_signals = signals_df[signals_df['date'] > portfolio.last_processed_date]
        print(f"    Processing {len(new_signals)} new signals")
    else:
        print(f"    Starting fresh with £{STARTING_CAPITAL:,}")
        new_signals = signals_df
    
    if len(new_signals) == 0:
        print(f"\n✅ Portfolio is up to date!")
        stats = portfolio.get_stats()
        
        print(f"\n  Current Status:")
        print(f"    Position:         {'LONG' if stats.get('current_position') == 1 else 'FLAT'}")
        if stats.get('current_position') == 1:
            print(f"    Entry Price:      ${stats.get('entry_price', 0):.2f}")
            print(f"    Unrealized P&L:   {stats.get('unrealized_pnl_pct', 0):+.2f}%")
        print(f"    Cash:             £{stats.get('current_cash', 0):,.0f}")
        print(f"    Total Equity:     £{stats.get('current_equity', 0):,.0f}")
        print(f"    Total Return:     {stats.get('total_return_pct', 0):+.2f}%")
        
        return
    
    # Process new signals
    print(f"\n[3] Processing trades...")
    for _, row in new_signals.iterrows():
        signal_info = format_signal_summary(row)
        portfolio.process_day(
            row['date'],
            row['gold_close'],
            int(row['model_position']),
            signal_info
        )
    
    # Save
    portfolio.save()
    
    # Display results
    stats = portfolio.get_stats()
    
    print(f"\n" + "="*80)
    print("PAPER PORTFOLIO RESULTS")
    print("="*80)
    
    print(f"\n📊 Portfolio Summary:")
    print(f"  Starting Capital: £{stats['starting_capital']:,.0f}")
    print(f"  Current Cash:     £{stats['current_cash']:,.0f}")
    print(f"  Current Equity:   £{stats['current_equity']:,.0f}")
    print(f"  Total Return:     {stats['total_return_pct']:+.2f}%")
    
    print(f"\n📈 Performance Metrics:")
    print(f"  Sharpe Ratio:     {stats['sharpe_ratio']:.3f}")
    print(f"  Max Drawdown:     {stats['max_drawdown_pct']:.2f}%")
    print(f"  Days Tracked:     {stats['days_tracked']}")
    
    print(f"\n💼 Position Status:")
    print(f"  Current Position: {'LONG' if stats['current_position'] == 1 else 'FLAT'}")
    if stats['current_position'] == 1:
        print(f"  Entry Price:      ${stats.get('entry_price', 0):.2f}")
        print(f"  Unrealized P&L:   {stats['unrealized_pnl_pct']:+.2f}%")
    
    print(f"\n🎯 Trading Stats:")
    print(f"  Total Trades:     {stats['total_trades']}")
    if stats['total_trades'] > 0:
        print(f"  Win Rate:         {stats['win_rate_pct']:.1f}%")
        print(f"  Avg Win:          {stats['avg_win_pct']:+.2f}%")
        print(f"  Avg Loss:         {stats['avg_loss_pct']:+.2f}%")
        print(f"  Avg Hold Period:  {stats['avg_days_held']:.1f} days")
    
    # Show recent trades
    if len(portfolio.trades) > 0:
        print(f"\n" + "="*80)
        print("RECENT TRADES (Last 5)")
        print("="*80)
        
        recent = pd.DataFrame(portfolio.trades).tail(5)
        recent['entry_date'] = recent['entry_date'].dt.date
        recent['exit_date'] = recent['exit_date'].dt.date
        
        display_cols = ['entry_date', 'exit_date', 'entry_price', 'exit_price', 
                       'pnl_pct', 'pnl_gbp', 'days_held']
        
        print("\n" + recent[display_cols].to_string(index=False))
    
    print(f"\n✅ Portfolio saved to {PORTFOLIO_FILE}")
    print("\n" + "="*80)


if __name__ == "__main__":
    main()
